name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: ðŸ“‚ Checkout main branch
        uses: actions/checkout@v3

      - name: ðŸ’Ž Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: ðŸ”¨ Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: ðŸ“¦ Generate cache key
        id: cache-key
        run: echo "::set-output name=key::${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“‚ Checkout _website branch
        uses: actions/checkout@v3
        with:
          ref: _website
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Ensures full history is fetched
          path: _website
        continue-on-error: true

      - name: ðŸ”„ Sync built site to _website branch
        run: |
          rsync -av --delete _site/ _website/

      - name: ðŸš€ Deploy to _website branch
        run: |
          cd _website
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy Jekyll site to _website branch" || true # this command will not fail if there's nothing to commit
          git push origin _website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}